obj-y += adsp.o
ifdef CONFIG_MACH_PHOTON
obj-y += adsp_info_photon.o
else
obj-y += adsp_info.o
endif
obj-y += adsp_driver.o
obj-y += adsp_video_verify_cmd.o
obj-y += adsp_videoenc_verify_cmd.o
obj-y += adsp_jpeg_verify_cmd.o adsp_jpeg_patch_event.o 
obj-y += adsp_vfe_verify_cmd.o adsp_vfe_patch_event.o 
obj-y += adsp_lpm_verify_cmd.o 
obj-y += audio_out.o audio_in.o audio_mp3.o audio_aac.o audmgr.o audpp.o audplay.o
ifdef CONFIG_MACH_PHOTON
obj-y += snd_photon.o
else
obj-y += snd.o
endif
obj-y += vocpcm.o
